"""add travel place detail fields

Revision ID: f0335f4a60b7
Revises: 9f2dbff29db2
Create Date: 2026-09-29 15:26:22.158430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0335f4a60b7'
down_revision = '9f2dbff29db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('restaurant_photos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nearby_photos', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_travel_places_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_places', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_travel_places_user_id_user'), type_='foreignkey')
        batch_op.drop_column('nearby_photos')
        batch_op.drop_column('restaurant_photos')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
